### ISSUE TITLE
allocated gpio.Pin is never closed

### ISSUE THREAD

**Issue by kaxori** [toitware/toit-pixel-strip#9]
in uart.toit line 113:
   tx := gpio.Pin.out pin    // pin is allocated, but never released

...

  close->none:
    port_.close     // used #primitive seems NOT to release the gpio

**Comment by kaxori** [comment]
**Workaround**:

class UartPixelStrip extends UartEncodingPixelStrip_:
  port_/uart.Port := ?
  **pin_ := ?**

...

constructor pixels/int --pin/int=17 --invert_pin/bool=true --bytes_per_pixel/int=3:
    tx := gpio.Pin.out pin
    **pin_ = tx**
...

 close->none:
    **pin_.close** 
    port_.close

**Comment by floitsch** [comment]
Thanks.
The strip class shouldn't just take a pin number, but a gpio.Pin instead.
However, for compatibility, we will still allow to take a pin number, and then correctly close the pin.

Uploading a fix.
